name = "PMFRGTest"
uuid = "cff97254-223f-4c84-9d94-0661ee15814f"
repo = "git@github.com:mmesiti/PMFRGTestRegistry.git"
description = "Test registry for PMFRG and subpackages"

[packages]
053fb7f8-31b7-4f68-aef8-4452b415dd8c = { name = "SpinFRGLattices", path = "S/SpinFRGLattices" }
307b9980-580b-4ffb-acf7-52430be9d54f = { name = "PMFRGCore", path = "P/PMFRGCore" }
